image: node:12-alpine

stages:
  - build
  - test
  - dockerise
  - deploy

cache:
  paths:
    - ./project-3b-frontend/node_modules/
    - ./project-3b-backend/node_modules/

build_react:
  stage: build
  tags:
    - comsc-ci
  script:
    - cd ./project-3b-frontend
    - npm install
    - npm run build
  only:
    - master
  artifacts:
    expire_in: 1 hour
    paths:
      - ./project-3b-frontend/node_modules/
      - ./project-3b-frontend/build/

build_node:
  stage: build
  tags:
    - comsc-ci
  script:
    - cd ./project-3b-backend
    - npm install
  only:
    - master
  artifacts:
    expire_in: 1 hour
    paths:
      - ./project-3b-backend/node_modules/

# test_react:
#   stage: test
#   tags:
#     - comsc-ci
#   script:
#     - cd ./project-3b-frontend
#     - CI=true npm test
#   only:
#     - master

# test_node:
#   stage: test
#   tags:
#     - comsc-ci
#   script:
#     - cd ./project-3b-backend
#     - CI=true npm test
#   only:
#     - master

docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: dockerise
  variables:
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  tags:
    - comsc-ci
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git.cf.ac.uk
    - cd ./project-3b-frontend
    - docker build -f Dockerfile.prod -t registry.git.cf.ac.uk/c1888037/project-3b .
    - docker push registry.git.cf.ac.uk/c1888037/project-3b
  # only:
  #   - master

openshift_deployment:
  image: openshift/origin-cli
  stage: deploy
  tags:
    - comsc-ci
  script:
    # - wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    # - tar xvzf oc.tar.gz
    # - rm oc.tar.gz
    # - mv oc kubectl /usr/local/bin/
    - oc login https://openshift.cs.cf.ac.uk:443 --token=$CI_OPENSHIFT_TOKEN
    - oc project workforce-planning-project || oc new-project workforce-planning-project
    # - oc create secret docker-registry docker-registry --docker-server=registry.git.cf.ac.uk --docker-username=C1888037 --docker-password=$CI_PASSWORD --docker-email=bhalal@cardiff.ac.uk
    # - oc create secret docker-registry git --docker-server=https://git.cardiff.ac.uk --docker-username=C1888037 --docker-password=$CI_PASSWORD --docker-email=bhalal@cardiff.ac.uk
    - oc secrets link default docker-registry git docker-registry --for=pull
    - oc import-image registry.git.cf.ac.uk/c1888037/project-3b --confirm
    - oc get service workforce-planning || oc new-app project-3b --name workforce-planning
    - oc expose service workforce-planning --port 3000
  # only:
  #   - master
