export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const TASK_CHANGE_START = 'TASK_CHANGE_START';
export const TASK_CHANGE_SUCCESS = 'TASK_CHANGE_SUCCESS';
export const TASK_CHANGE_FAIL = 'TASK_CHANGE_FAIL';

export const SET_DEMO_DATA = 'SET_DEMO_DATA';
